name: Pull requests
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm i
      - name: Code analysis
        run: |
          npx ts-standard
      - name: Test
        run: |
          npm run test
